name: unittest
on:
  - push

jobs:
  unittest:
    runs-on: ubuntu-latest
    container:
      image: golang:1.20
    steps:
      - uses: actions/checkout@v2
      - name: unittest
        env:
          TEST_BASIC_AUTH_USERNAME: takutakahashi
          TEST_BASIC_AUTH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go test ./pkg/gtc/
      
