name: unittest
on:
  - push

jobs:
  unittest:
    runs-on: ubuntu-latest
    container:
      image: golang:1.17
    steps:
      - uses: actions/checkout@v2
      - name: unittest
        run: |
          go test ./pkg/gtc/
      
